---
name: IPAM management
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ipam.sh
      - azure-pipeline.yaml
      - function.sh

pr: none # Disable pull request triggers.

variables:
  - name: service_connection
    value: dts-management-prod-intsvc

jobs:
  - job: Run
    timeoutInMinutes: 20
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: AzureCLI@2
        displayName: 'Run ipam manage script'
        inputs:
          scriptType: bash
          scriptPath: ./ipam.sh
          azureSubscription: ${{ variables.service_connection }}