---
name: IPAM - Sync Vnets & External Routes
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
      - ./external.sh
      - ./external-sync-pipeline.yaml
      - ./sync-vnets.sh
      - ./function.sh
      - ./findoverlapping.py
schedules:
  - cron: '0 3 * * *'
    displayName: Runs 3 AM everyday
    branches:
      include:
        - master
    always: 'true'

pr: none # Disable pull request triggers.

variables:
  - name: service_connection
    value: dts-management-prod-intsvc


jobs:
  - job: RunSyncScripts
    timeoutInMinutes: 20
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: AzureCLI@2
        displayName: 'Sync vnets Script'
        inputs:
          scriptType: bash
          scriptPath: ./sync-vnets.sh
          azureSubscription: ${{ variables.service_connection }}
      - task: AzureCLI@2
        displayName: 'Sync External Effective Routes'
        inputs:
          scriptType: bash
          scriptPath: ./external.sh
          azureSubscription: ${{ variables.service_connection }}