---
name: IPAM - Sync External CIDRs
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
      - ./external.sh
      - external-sync-pipeline.yaml
schedules:
  - cron: '0 3 * * *'
    displayName: Runs 3 AM everyday
    branches:
      include:
        - master
    always: 'true'

pr: none # Disable pull request triggers.

variables:
  - name: service_connection
    value: dts-management-prod-intsvc


jobs:
  - job: RunExternalScript
    timeoutInMinutes: 20
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: AzureCLI@2
        displayName: 'Run External Script'
        inputs:
          scriptType: bash
          scriptPath: ./external.sh
          azureSubscription: ${{ variables.service_connection }}