name: External CIDR Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Every day at 3am BST
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: c9004151-4f22-434c-800a-b2bddcea5a7b # ipam
          tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
          allow-no-subscriptions: true
      - name: Run external sync script
        run: ./external.sh